-module(openpixie_sup).
-behaviour(supervisor).

-export([start_link/0]).
-export([init/1]).

start_link() ->
    supervisor:start_link({local, ?MODULE}, ?MODULE, []).

init([]) ->
    Children = [
        #{id => openpixie_auth,
          start => {openpixie_auth, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_auth]},
        #{id => openpixie_permissions,
          start => {openpixie_permissions, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_permissions]},
        #{id => openpixie_circuit_breaker,
          start => {openpixie_circuit_breaker, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_circuit_breaker]},
        #{id => openpixie_semaphore,
          start => {openpixie_semaphore, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_semaphore]},
        #{id => openpixie_skills,
          start => {openpixie_skills, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_skills]},
        #{id => openpixie_memory,
          start => {openpixie_memory, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_memory]},
        #{id => openpixie_channel,
          start => {openpixie_channel, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_channel]},
        #{id => openpixie_topic_store,
          start => {openpixie_topic_store, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_topic_store]},
        #{id => openpixie_cron,
          start => {openpixie_cron, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_cron]},
        #{id => openpixie_metrics,
          start => {openpixie_metrics, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_metrics]},
        #{id => openpixie_archive,
          start => {openpixie_archive, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => worker,
          modules => [openpixie_archive]},
        #{id => openpixie_topic_sup,
          start => {openpixie_topic_sup, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => supervisor,
          modules => [openpixie_topic_sup]},
        #{id => openpixie_http,
          start => {openpixie_http, start_link, []},
          restart => permanent,
          shutdown => 5000,
          type => supervisor,
          modules => [openpixie_http]}
    ],
    {ok, {#{strategy => one_for_one, intensity => 5, period => 60}, Children}}.